# Generated by Django 4.2.30 on 2026-09-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='pasted.py', max_length=200)),
                ('code', models.TextField()),
                ('status', models.CharField(default='QUEUED', max_length=12)),
                ('stage', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('line', models.IntegerField()),
                ('rule', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=40)),
                ('what', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
                ('how', models.TextField(blank=True)),
                ('fix_diff', models.TextField(blank=True)),
                ('validation', models.CharField(blank=True, max_length=12)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='analysis.analysis')),
            ],
        ),
    ]
